"""Trunk pitch is just a value of config/home_pose.yaml (generated by training).

tests/fixtures/home_pose_forward_lean.yaml is what mjlab_microban home-config's
write-robot generates for the forward-lean HOME (trunk +10 deg).  With it the
runtime has exactly the constants of robot branch forward-lean-home; with
tests/fixtures/home_pose_centered.yaml (the centered config/home_pose.yaml,
frozen so this test holds on a branch of any HOME) it has the centered ones.
The posture rules follow the HOME gravity: settle / stand are measured from
HOME_PROJECTED_GRAVITY, falls stay physical (from vertical), and the neck
stabilisation reference is the HOME trunk pitch.  Which policies each HOME
accepts is test_policy_contract.py (the policies carry their HOME stamp).

Each case runs in a subprocess (MICROBAN_HOME_POSE_YAML selects the HOME).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import unittest
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
LEAN_YAML = REPO_ROOT / "tests" / "fixtures" / "home_pose_forward_lean.yaml"
CENTERED_YAML = REPO_ROOT / "tests" / "fixtures" / "home_pose_centered.yaml"

PROBE = r"""
import json, sys, math
import constants, home_pose, policy_contract, scheduler

s = scheduler.Scheduler.__new__(scheduler.Scheduler)
s._settle_threshold = -math.cos(math.radians(scheduler.GETUP_HANDBACK_SETTLE_TILT_DEG))
s._settle_tilt_rad = math.radians(scheduler.GETUP_HANDBACK_SETTLE_TILT_DEG)
s._stand_threshold = -0.9
s._stand_tilt_rad = math.radians(scheduler.GETUP_STAND_TILT_DEG)

def gravity(pitch_deg):
    p = math.radians(pitch_deg)
    return [math.sin(p), 0.0, -math.cos(p)]

print(json.dumps({
    "trunk": constants.HOME_TRUNK_PITCH_RAD,
    "hip": constants.HOME_HIP_PITCH_RAD,
    "ankle": constants.HOME_ANKLE_PITCH_RAD,
    "root_z": constants.HOME_ROOT_POS_Z_M,
    "quat": list(constants.HOME_ROOT_QUAT_WXYZ),
    "gravity": list(constants.HOME_PROJECTED_GRAVITY),
    "neutral": constants.NEUTRAL_POSE,
    "tag": home_pose.HOME_TAG,
    "pico_frame": policy_contract.PICO_TARGET_FRAME,
    "hand_fk_revision": home_pose.hand_target_fk_contract()["revision"],
    "settled": {str(p): s._settled(gravity(p)) for p in (-15, -5, 0, 5, 10, 15, 20, 25)},
    "standing": {str(p): s._standing(gravity(p)) for p in (-30, -20, -15, 0, 10, 30, 35, 40)},
    "tilt_at_home": home_pose.tilt_from_home_rad(constants.HOME_PROJECTED_GRAVITY),
}))
"""


def _probe(yaml_path: Path) -> dict:
    environment = dict(os.environ)
    environment["MICROBAN_HOME_POSE_YAML"] = str(yaml_path)
    environment["PYTHONPATH"] = os.pathsep.join(
        [str(REPO_ROOT / "src"), *filter(None, [os.environ.get("PYTHONPATH")])]
    )
    completed = subprocess.run(
        [sys.executable, "-c", PROBE],
        env=environment, cwd=REPO_ROOT, capture_output=True, text=True, timeout=600, check=False,
    )
    if completed.returncode != 0:
        raise AssertionError(completed.stderr[-3000:])
    return json.loads(completed.stdout.strip().splitlines()[-1])


class AnyTrunkHomeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.lean = _probe(LEAN_YAML)
        cls.centered = _probe(CENTERED_YAML)

    def test_forward_lean_constants_are_the_forward_lean_home_branch(self):
        lean = self.lean
        trunk = float(np.deg2rad(10.0))
        hip = float(np.deg2rad(-14.166561199931119))
        ankle = float(np.deg2rad(4.127976841869204))
        self.assertEqual(lean["trunk"], trunk)
        self.assertEqual(lean["hip"], hip)
        self.assertEqual(lean["ankle"], ankle)
        self.assertEqual(lean["root_z"], 0.170430569776402)
        self.assertEqual(
            lean["quat"],
            [float(np.cos(trunk / 2.0)), 0.0, float(np.sin(trunk / 2.0)), 0.0],
        )
        self.assertEqual(
            lean["gravity"], [float(np.sin(trunk)), 0.0, -float(np.cos(trunk))]
        )
        expected_neutral = {
            "left_hip_yaw": 0.0, "left_hip_roll": float(np.deg2rad(5.0)),
            "left_hip_pitch": hip, "left_knee": 0.0, "left_ankle_pitch": ankle,
            "left_ankle_roll": float(np.deg2rad(-5.0)), "right_hip_yaw": 0.0,
            "right_hip_roll": float(np.deg2rad(-5.0)), "right_hip_pitch": hip,
            "right_knee": 0.0, "right_ankle_pitch": ankle,
            "right_ankle_roll": float(np.deg2rad(5.0)), "left_shoulder_pitch": 0.0,
            "left_shoulder_roll": float(np.deg2rad(10.0)),
            "left_elbow": float(np.deg2rad(-20.0)), "right_shoulder_pitch": 0.0,
            "right_shoulder_roll": float(np.deg2rad(-10.0)),
            "right_elbow": float(np.deg2rad(-20.0)), "head": 0.0, "neck_roll": 0.0,
            "neck_pitch": 0.0,
        }
        self.assertEqual(lean["neutral"], expected_neutral)
        self.assertEqual(lean["tag"], "forward_lean_home")
        self.assertEqual(lean["pico_frame"], "robot_home_levelled_trunk_xyz_forward_left_up")
        self.assertEqual(
            lean["hand_fk_revision"],
            "microban_robot_xml_arm_fk_reachable_box_elbow_upper_minus10_"
            "home_levelled_lean10_receiver_box64mm_v4",
        )

    def test_centered_constants_are_unchanged(self):
        centered = self.centered
        self.assertEqual(centered["trunk"], 0.0)
        self.assertEqual(centered["gravity"], [0.0, 0.0, -1.0])
        self.assertEqual(centered["quat"], [1.0, 0.0, 0.0, 0.0])
        self.assertEqual(centered["tag"], "centered_home")
        self.assertEqual(centered["pico_frame"], "robot_trunk_xyz_forward_left_up")

    def test_settle_and_stand_are_measured_from_home_gravity(self):
        # Forward-lean HOME: settled within 12 deg of the 10 deg lean, so a
        # vertical trunk (10 deg off) still settles and 25 deg forward does not.
        self.assertEqual(
            self.lean["settled"],
            {"-15": False, "-5": False, "0": True, "5": True, "10": True, "15": True,
             "20": True, "25": False},
        )
        self.assertEqual(self.lean["tilt_at_home"], 0.0)
        # Stand: within acos(0.9) = 25.8 deg of HOME.
        self.assertEqual(
            self.lean["standing"],
            {"-30": False, "-20": False, "-15": True, "0": True, "10": True, "30": True,
             "35": True, "40": False},
        )
        # Centered HOME: the original vertical rules (gz < -cos 12 deg, gz < -0.9).
        self.assertEqual(
            self.centered["settled"],
            {"-15": False, "-5": True, "0": True, "5": True, "10": True, "15": False,
             "20": False, "25": False},
        )
        self.assertEqual(
            self.centered["standing"],
            {"-30": False, "-20": True, "-15": True, "0": True, "10": True, "30": False,
             "35": False, "40": False},
        )


if __name__ == "__main__":
    unittest.main()
