# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 Marc Duclusaud

from home_pose import (
    HOME_JOINT_POS_RAD as _HOME_JOINT_POS_RAD,
    HOME_ROOT_POS_M as _HOME_ROOT_POS_M,
    HOME_ROOT_QUAT_WXYZ as _HOME_ROOT_QUAT_WXYZ,
)

MOTOR_TO_ID = {
    "left_hip_yaw": 11,
    "left_hip_roll": 12,
    "left_hip_pitch": 13,
    "left_knee": 14,
    "left_ankle_pitch": 15,
    "left_ankle_roll": 16,
    "right_hip_yaw": 21,
    "right_hip_roll": 22,
    "right_hip_pitch": 23,
    "right_knee": 24,
    "right_ankle_pitch": 25,
    "right_ankle_roll": 26,
    "left_shoulder_pitch": 31,
    "left_shoulder_roll": 32,
    "left_elbow": 33,
    "right_shoulder_pitch": 41,
    "right_shoulder_roll": 42,
    "right_elbow": 43,
    "head": 51,
    "neck_roll": 52,
    "neck_pitch": 53,
}

ID_TO_MOTOR = {v: k for k, v in MOTOR_TO_ID.items()}

# The reference pose of every neutral return on the robot: the HOME of the
# training repository, read from config/home_pose.yaml (generated by
# mjlab_microban's config/home_pose_tool.py write-robot; see src/home_pose.py).
# Trunk pose of HOME in the training scene: the lowest sole collision corner
# touches the ground at this z; root quaternion pitched by the HOME trunk
# pitch about y (w-x-y-z).
HOME_ROOT_POS_Z_M = _HOME_ROOT_POS_M[2]
HOME_ROOT_QUAT_WXYZ = _HOME_ROOT_QUAT_WXYZ
# Robot motor order (MOTOR_TO_ID), radians.
NEUTRAL_POSE = {name: _HOME_JOINT_POS_RAD[name] for name in MOTOR_TO_ID}

MOTOR_SIGN = {
    "left_hip_yaw": -1.0,
    "left_hip_roll": 1.0,
    "left_hip_pitch": -1.0,
    "left_knee": 1.0,
    "left_ankle_pitch": 1.0,
    "left_ankle_roll": -1.0,
    "right_hip_yaw": -1.0,
    "right_hip_roll": 1.0,
    "right_hip_pitch": 1.0,
    "right_knee": -1.0,
    "right_ankle_pitch": -1.0,
    "right_ankle_roll": -1.0,
    "left_shoulder_pitch": 1.0,
    "left_shoulder_roll": -1.0,
    "left_elbow": 1.0,
    "right_shoulder_pitch": -1.0,
    "right_shoulder_roll": -1.0,
    "right_elbow": -1.0,
    "head": 1.0,
    # neck_roll / neck_pitch signs are CAD-inferred, not yet measured on real
    # hardware: on both servos, the idler-horn/idle-cap hardware sits at the low end of the
    # joint's rotation axis (x for roll, y for pitch), so the driven/output face was taken to
    # be the high end, matching the +X / +Y directions already used as the joint axes in the
    # URDF. Combined with DYNAMIXEL's positive-direction convention (CCW viewed from the horn
    # side), that gives +1.0 for both. Verify with a small test motion before trusting this for
    # full-range moves.
    "neck_roll": 1.0,
    "neck_pitch": 1.0,
}

# Position P Gain (Dynamixel register value)
KP_DEFAULT: int = 400        # ~0.886 Nm/rad in MuJoCo
KP_RL: int = 125             # ~0.277 Nm/rad in MuJoCo
KP_GAIN_PRM: float = 0.0022  # Nm/rad per register unit (for Xl330)

# BAM motor model (bam package) of the XC330-T288-T servos on a 3S pack. bam has
# no published XC330-T288-T identification: tools/actuator_id/ defines the
# actuator and records and fits a pendulum identification (xc330_params.json).
# PROXY_KT / PROXY_R below are that fit (m6 model, 30 logs, score 0.064 rad).
# BAM_MAX_CURRENT is the Robotis datasheet current limit.
BAM_VIN: float = 11.1        # 3S nominal (3x3.7V); matches XC330-T288-T's own rated voltage
BAM_VIN_MIN: float = 9.0     # 3S practical minimum (3x3.0V/cell)
BAM_VOLTAGE_DROP_GAIN: float = 0.2  # bam fit for XL330, kept for XC330
BAM_MAX_CURRENT: float = 0.91 # XC330-T288-T firmware current limit [A] (Robotis control table: 910 mA)

# Overcurrent safety: emergency torque-off when the summed |present_current| of all
# motors stays above OVERCURRENT_CUTOFF_A for OVERCURRENT_DEBOUNCE_TICKS consecutive ticks.
# Goal: cut the robot before a current spike (e.g. all motors snapping during a fall) trips the BMS.
PRESENT_CURRENT_UNIT_A: float = 0.001   # XL330 present_current register unit (1.0 mA/LSB)
OVERCURRENT_CUTOFF_A: float = 15.0      # total pack current threshold (CALIBRATE: below BMS trip, above normal walk peak)
OVERCURRENT_DEBOUNCE_TICKS: int = 2     # consecutive over-threshold ticks before cutting

# Current proxy used when present_current is NOT read (Observer.observe_current = False), so the
# safety needs no extra bus transaction. Reproduces the bam XL330 m6 voltage-controlled model from
# data already read (present_position, present_velocity) and the command target:
#   duty = clip(PROXY_KP * PROXY_ERROR_GAIN * (target - q), ±PROXY_MAX_PWM)
#   I    = (PROXY_VIN * duty - PROXY_KT * dq) / PROXY_R      then |I| capped at BAM_MAX_CURRENT
PROXY_KT: float = 1.043                  # XC330-T288-T torque constant [Nm/A] (tools/actuator_id fit)
PROXY_R: float = 10.007                  # XC330-T288-T coil resistance [Ohm] (tools/actuator_id fit)
PROXY_VIN: float = BAM_VIN               # supply voltage [V]
PROXY_ERROR_GAIN: float = 0.0028773775   # duty cycle per (kp * rad), XL330 encoder/gain scaling
PROXY_MAX_PWM: float = 1.0               # max duty cycle magnitude
PROXY_KP: int = KP_RL                    # firmware P gain assumed by the proxy (walking regime)
OVERCURRENT_PROXY_DELAY_TICKS: int = 3   # number of ticks to delay the proxy current estimate

# Velocity command limits [m/s, m/s, rad/s], applied centrally to every input source.
# Input sources emit normalized commands in [-1, 1]; scale_velocity() maps them to these.
# Rotation gets a wider range when turning in place (vx = vy = 0) than while translating.
VX_MAX: float = 0.7
VX_MAX_BACKWARD: float = 0.5  # backward (vx < 0) is capped lower than forward
VY_MAX: float = 0.3
VTHETA_MAX_STATIONARY: float = 3.0
VTHETA_MAX_MOVING: float = 1.5

# IMU (BMI088) I2C bus number on the Raspberry Pi
IMU_I2C_BUS: int = 1

# Rotation from trunk frame (body) to IMU sensor frame
IMU_MOUNT_QUAT: tuple[float, float, float, float] = (0.5, -0.5, -0.5, 0.5)

# Observation DoF ordering
OBSERVATION_DOF_ORDER = [
    "right_shoulder_pitch",
    "right_shoulder_roll",
    "right_elbow",
    "right_hip_yaw",
    "right_hip_roll",
    "right_hip_pitch",
    "right_knee",
    "right_ankle_pitch",
    "right_ankle_roll",
    "left_shoulder_pitch",
    "left_shoulder_roll",
    "left_elbow",
    "left_hip_yaw",
    "left_hip_roll",
    "left_hip_pitch",
    "left_knee",
    "left_ankle_pitch",
    "left_ankle_roll"
]
