# SPDX-License-Identifier: GPL-3.0-or-later
"""The HOME pose shared by every policy, read from config/home_pose.yaml.

config/home_pose.yaml is GENERATED by the training repository
(mjlab_microban ``config/home_pose_tool.py write-robot``) from its single HOME
source ``config/home_pose.yaml``; the robot runtime has no MuJoCo, so every
derived value it needs is in the file: the joint angles (radians, bit-exact
with training), root position/quaternion, projected gravity at HOME and the
HOME-bound contract identifiers each deployed policy must carry.

The file is a strict YAML subset parsed here without PyYAML: ``#`` comment
lines, ``key:`` lines opening a nested mapping (two-space indent) and
``key: <JSON value>`` lines.
"""

from __future__ import annotations

import json
import math
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType
from typing import Any

import numpy as np

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
HOME_POSE_PATH = REPOSITORY_ROOT / "config" / "home_pose.yaml"
HOME_POSE_SCHEMA_VERSION = 1

HOME_JOINT_NAMES = (
    "head",
    "neck_roll",
    "neck_pitch",
    "left_shoulder_roll",
    "right_shoulder_roll",
    "left_shoulder_pitch",
    "right_shoulder_pitch",
    "left_elbow",
    "right_elbow",
    "left_hip_roll",
    "right_hip_roll",
    "left_hip_pitch",
    "right_hip_pitch",
    "left_hip_yaw",
    "right_hip_yaw",
    "left_knee",
    "right_knee",
    "left_ankle_roll",
    "right_ankle_roll",
    "left_ankle_pitch",
    "right_ankle_pitch",
)
CONTRACT_KEYS = (
    "walk_contract_version",
    "v12_home_pose_revision",
    "v12_recipe_revision",
    "v12_hand_pose_release_recipe_revision",
    "v12_packager_revision",
)
# A deployed policy's recorded HOME must reproduce this file to these
# tolerances (the get-up and walking checks).
HOME_POSE_STAMP_TOLERANCE_RAD = 1.0e-6
HOME_ROOT_STAMP_TOLERANCE = 1.0e-6


class HomePoseConfigError(ValueError):
    """config/home_pose.yaml is missing, malformed or inconsistent."""


def parse_home_pose_yaml(text: str, *, source: str = "<text>") -> dict[str, Any]:
    """Parse the generated HOME YAML subset into nested dicts."""

    root: dict[str, Any] = {}
    # (indent of the mapping's keys, mapping); a "key:" line with no value
    # opens a child mapping whose keys are indented two more spaces.
    stack: list[tuple[int, dict[str, Any]]] = [(0, root)]
    pending: tuple[int, dict[str, Any]] | None = None
    for number, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if raw[indent:indent + 1] == "\t":
            raise HomePoseConfigError(f"{source}:{number}: tabs are not allowed")
        if pending is not None:
            if indent == pending[0]:
                stack.append(pending)
            pending = None
        while len(stack) > 1 and indent < stack[-1][0]:
            stack.pop()
        if indent != stack[-1][0]:
            raise HomePoseConfigError(f"{source}:{number}: bad indentation")
        key, separator, value = stripped.partition(":")
        if not separator or not key.replace("_", "a").isalnum():
            raise HomePoseConfigError(f"{source}:{number}: expected 'key: value'")
        parent = stack[-1][1]
        if key in parent:
            raise HomePoseConfigError(f"{source}:{number}: duplicate key {key!r}")
        value = value.strip()
        if not value:
            child: dict[str, Any] = {}
            parent[key] = child
            pending = (indent + 2, child)
            continue
        try:
            parent[key] = json.loads(value)
        except json.JSONDecodeError as error:
            raise HomePoseConfigError(f"{source}:{number}: bad value {value!r}") from error
    return root


def _float_list(document: Mapping[str, Any], key: str, length: int) -> tuple[float, ...]:
    value = document.get(key)
    if (
        not isinstance(value, list)
        or len(value) != length
        or not all(isinstance(item, (int, float)) and not isinstance(item, bool) for item in value)
        or not all(math.isfinite(float(item)) for item in value)
    ):
        raise HomePoseConfigError(f"{key} must be {length} finite numbers")
    return tuple(float(item) for item in value)


def _joint_mapping(document: Mapping[str, Any], key: str) -> dict[str, float]:
    value = document.get(key)
    if not isinstance(value, Mapping) or set(value) != set(HOME_JOINT_NAMES):
        raise HomePoseConfigError(f"{key} must name exactly the 21 Microban joints")
    result = {}
    for name in HOME_JOINT_NAMES:
        angle = value[name]
        if isinstance(angle, bool) or not isinstance(angle, (int, float)):
            raise HomePoseConfigError(f"{key}.{name} must be a number")
        if not math.isfinite(float(angle)):
            raise HomePoseConfigError(f"{key}.{name} must be finite")
        result[name] = float(angle)
    return result


def load_home_pose(path: Path | str = HOME_POSE_PATH) -> dict[str, Any]:
    """Read and cross-check config/home_pose.yaml; return the validated values."""

    path = Path(path)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise HomePoseConfigError(f"cannot read {path}: {error}") from error
    document = parse_home_pose_yaml(text, source=str(path))
    if document.get("schema_version") != HOME_POSE_SCHEMA_VERSION:
        raise HomePoseConfigError(f"{path}: unsupported schema_version")
    degrees = _joint_mapping(document, "joint_pos_deg")
    radians = _joint_mapping(document, "joint_pos_rad")
    for name in HOME_JOINT_NAMES:
        if float(np.deg2rad(degrees[name])) != radians[name]:
            raise HomePoseConfigError(f"{path}: joint_pos_rad.{name} is not joint_pos_deg in radians")
    pitch_deg = document.get("trunk_pitch_deg")
    pitch_rad = document.get("trunk_pitch_rad")
    if (
        not isinstance(pitch_deg, (int, float))
        or not isinstance(pitch_rad, (int, float))
        or float(np.deg2rad(float(pitch_deg))) != float(pitch_rad)
    ):
        raise HomePoseConfigError(f"{path}: trunk_pitch_deg/trunk_pitch_rad are inconsistent")
    pitch = float(pitch_rad)
    # The runtime's neck stabilisation, stand/settle checks and policy smoke
    # observations measure tilt from vertical: only an upright trunk at HOME
    # is supported.
    if pitch != 0.0:
        raise HomePoseConfigError(
            f"{path}: trunk_pitch_deg={pitch_deg!r}; this runtime supports only a vertical "
            "trunk at HOME"
        )
    root_pos = _float_list(document, "root_pos_m", 3)
    root_quat = _float_list(document, "root_quat_wxyz", 4)
    gravity = _float_list(document, "projected_gravity", 3)
    expected_quat = (float(np.cos(0.5 * pitch)), 0.0, float(np.sin(0.5 * pitch)), 0.0)
    expected_gravity = (float(np.sin(pitch)), 0.0, float(-np.cos(pitch)))
    if root_quat != expected_quat or gravity != expected_gravity:
        raise HomePoseConfigError(f"{path}: root quaternion/gravity do not match the trunk pitch")
    if root_pos[:2] != (0.0, 0.0) or not 0.1 < root_pos[2] < 0.3:
        raise HomePoseConfigError(f"{path}: implausible HOME root position {root_pos}")
    contracts = document.get("contracts")
    if not isinstance(contracts, Mapping) or set(contracts) != set(CONTRACT_KEYS) or not all(
        isinstance(contracts[key], str) and contracts[key] for key in CONTRACT_KEYS
    ):
        raise HomePoseConfigError(f"{path}: contracts must name {list(CONTRACT_KEYS)}")
    hand_target_fk = document.get("hand_target_fk")
    if not isinstance(hand_target_fk, Mapping) or not hand_target_fk:
        raise HomePoseConfigError(f"{path}: hand_target_fk is missing")
    arm_home = [
        [
            float(np.rad2deg(radians[f"{side}_{joint}"]))
            for joint in ("shoulder_pitch", "shoulder_roll", "elbow")
        ]
        for side in ("left", "right")
    ]
    if hand_target_fk.get("home_joint_deg") != [
        [degrees[f"{side}_{joint}"] for joint in ("shoulder_pitch", "shoulder_roll", "elbow")]
        for side in ("left", "right")
    ] or not np.allclose(arm_home, hand_target_fk["home_joint_deg"], rtol=0.0, atol=1e-9):
        raise HomePoseConfigError(f"{path}: hand_target_fk.home_joint_deg is not the arm HOME")
    for key in ("name", "label", "tag", "joint_hash"):
        if not isinstance(document.get(key), str) or not document[key]:
            raise HomePoseConfigError(f"{path}: {key} must be a non-empty string")
    return {
        "path": path,
        "name": document["name"],
        "label": document["label"],
        "tag": document["tag"],
        "joint_hash": document["joint_hash"],
        "trunk_pitch_rad": pitch,
        "joint_pos_deg": MappingProxyType(degrees),
        "joint_pos_rad": MappingProxyType(radians),
        "root_pos_m": root_pos,
        "root_quat_wxyz": root_quat,
        "projected_gravity": gravity,
        "contracts": MappingProxyType(dict(contracts)),
        "hand_target_fk": hand_target_fk,
    }


HOME_POSE = load_home_pose()

HOME_JOINT_POS_RAD: Mapping[str, float] = HOME_POSE["joint_pos_rad"]
HOME_TRUNK_PITCH_RAD: float = HOME_POSE["trunk_pitch_rad"]
HOME_ROOT_POS_M: tuple[float, float, float] = HOME_POSE["root_pos_m"]
HOME_ROOT_QUAT_WXYZ: tuple[float, float, float, float] = HOME_POSE["root_quat_wxyz"]
HOME_PROJECTED_GRAVITY: tuple[float, float, float] = HOME_POSE["projected_gravity"]
HOME_CONTRACTS: Mapping[str, str] = HOME_POSE["contracts"]
HOME_TAG: str = HOME_POSE["tag"]


def hand_target_fk_contract() -> dict[str, Any]:
    """A fresh copy of the training exporter's hand-target FK contract."""

    return json.loads(json.dumps(HOME_POSE["hand_target_fk"]))


def home_pose_stamp_matches(value: str | None) -> bool:
    """True when a policy's recorded HOME JSON is this HOME.

    ``value`` is the exporters' ``{"joint_pos_rad": {...}, "root_pos_m": [...],
    "root_quat_wxyz": [...]}`` stamp (get-up ``microban_getup_home_pose``,
    walking ``home_pose``).
    """

    if not value:
        return False
    try:
        home = json.loads(value)
        joints = {str(name): float(angle) for name, angle in home["joint_pos_rad"].items()}
        root_pos = [float(item) for item in home["root_pos_m"]]
        root_quat = [float(item) for item in home["root_quat_wxyz"]]
    except (TypeError, ValueError, KeyError, AttributeError, OverflowError):
        return False
    return (
        set(joints) == set(HOME_JOINT_POS_RAD)
        and all(
            math.isfinite(angle)
            and abs(angle - HOME_JOINT_POS_RAD[name]) <= HOME_POSE_STAMP_TOLERANCE_RAD
            for name, angle in joints.items()
        )
        and len(root_pos) == 3
        and all(
            abs(actual - expected) <= HOME_ROOT_STAMP_TOLERANCE
            for actual, expected in zip(root_pos, HOME_ROOT_POS_M)
        )
        and len(root_quat) == 4
        and all(
            abs(actual - expected) <= HOME_ROOT_STAMP_TOLERANCE
            for actual, expected in zip(root_quat, HOME_ROOT_QUAT_WXYZ)
        )
    )
